version: "3.9"

networks:
  external-network:
    name: external-network
    driver: bridge

services:
  web-alpine:
    build:
      context: .
      dockerfile: dockerfile
      labels:
      - "com.centurylinklabs.watchtower.enable=false"
    command: npm start
    ports:
    - 5055:5000
    restart: unless-stopped
    networks:
      - external-network