version: "3.9"

networks:
  interlink:
    external: true

services:
  web-alpine:
    image: ghcr.io/liukonen/riverscriptbackend-go-edition:main
    command: npm start
    ports:
    - 5055:5000
    restart: unless-stopped
    networks:
      - interlink
